- name: total_hosts
  help: Total hosts count
  path: $.total_hosts
  labels:
    app: foreman 

- name: bad_hosts
  help: Hosts with error state
  path: $.bad_hosts
  labels:
    app: foreman 

- name: bad_hosts_enabled
  help: Hosts with error state and alerts enabled
  path: $.bad_hosts_enabled
  labels:
    app: foreman 

- name: active_hosts
  help: Hosts which recently applied changes
  path: $.active_hosts
  labels:
    app: foreman 

- name: active_hosts_ok
  help: Hosts which recently applied changes successfully
  path: $.active_hosts_ok
  labels:
    app: foreman 

- name: active_hosts_ok_enabled
  help: Hosts which recently applied changes successfully with alerts enabled
  path: $.active_hosts_ok_enabled
  labels:
    app: foreman 

- name: ok_hosts
  help: Hosts without changes or errors
  path: $.ok_hosts
  labels:
    app: foreman 

- name: ok_hosts_enabled
  help: Hosts without changes or errors, with alerts enabled
  path: $.ok_hosts_enabled
  labels:
    app: foreman 

- name: out_of_sync_hosts
  help: Out of sync hosts
  path: $.out_of_sync_hosts
  labels:
    app: foreman 

- name: out_of_sync_hosts_enabled
  help: Out of sync hosts with alerts enabled
  path: $.out_of_sync_hosts_enabled
  labels:
    app: foreman 

- name: disabled_hosts
  help: Hosts with alerts disabled
  path: $.disabled_hosts
  labels:
    app: foreman 

- name: pending_hosts
  help: Hosts that had pending changes
  path: $.pending_hosts
  labels:
    app: foreman 

- name: pending_hosts_enabled
  help: Hosts that had pending changes with alerts enabled
  path: $.pending_hosts_enabled
  labels:
    app: foreman 

- name: good_hosts
  help: Hosts without errors
  path: $.good_hosts
  labels:
    app: foreman 

- name: good_hosts_enabled
  help: Hosts without errors, with alerts enabled
  path: $.good_hosts_enabled
  labels:
    app: foreman 

- name: reports_missing
  help: Hosts which are not reporting
  path: $.reports_missing
  labels:
    app: foreman 